//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreySutton.Xrm.Utilities.Resources.ConsoleCrmCredentialManager
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreySutton.Xrm.Utilities.Resources.ConsoleCrmCredentialManager.Error" +
                            "s", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must not be empty (Error #100-14).
        /// </summary>
        internal static string Error_InvalidIsOffice365_Empty
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidIsOffice365_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must be yes/no (Error #100-13).
        /// </summary>
        internal static string Error_InvalidIsOffice365_NotYesNo
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidIsOffice365_NotYesNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid organization name: input must not be empty (Error #100-6).
        /// </summary>
        internal static string Error_InvalidOrganizationName_Empty
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidOrganizationName_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid region: input must not be empty (Error #100-3).
        /// </summary>
        internal static string Error_InvalidRegion_Empty
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidRegion_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid region: option must be between 0 and 9 (Error #100-4).
        /// </summary>
        internal static string Error_InvalidRegion_OutOfRange
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidRegion_OutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid region: failed to parse option (Error #100-5).
        /// </summary>
        internal static string Error_InvalidRegion_ParseFail
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidRegion_ParseFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must not be empty (Error #100-13).
        /// </summary>
        internal static string Error_InvalidShouldSaveCredentials_Empty
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidShouldSaveCredentials_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must be yes/no (Error #100-14).
        /// </summary>
        internal static string Error_InvalidShouldSaveCredentials_NotYesNo
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidShouldSaveCredentials_NotYesNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must not be empty (Error #100-7).
        /// </summary>
        internal static string Error_InvalidUniqueInstance_Empty
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidUniqueInstance_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must be yes/no (Error #100-8).
        /// </summary>
        internal static string Error_InvalidUniqueInstance_NotYesNo
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidUniqueInstance_NotYesNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must not be empty (Error #100-12).
        /// </summary>
        internal static string Error_InvalidUseAdvancedSetup_Empty
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidUseAdvancedSetup_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must be yes/no (Error #100-11).
        /// </summary>
        internal static string Error_InvalidUseAdvancedSetup_NotYesNo
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidUseAdvancedSetup_NotYesNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid username: input must not be empty (Error #100-1).
        /// </summary>
        internal static string Error_InvalidUsername_Empty
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidUsername_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid username: username must contain &apos;@&apos; (Error #100-2).
        /// </summary>
        internal static string Error_InvalidUsername_NoAt
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidUsername_NoAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must not be empty (Error #100-15).
        /// </summary>
        internal static string Error_InvalidUseSavedCredentials_Empty
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidUseSavedCredentials_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must be yes/no (Error #100-16).
        /// </summary>
        internal static string Error_InvalidUseSavedCredentials_NotYesNo
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidUseSavedCredentials_NotYesNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must not be empty (Error #100-9).
        /// </summary>
        internal static string Error_InvalidUseSsl_Empty
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidUseSsl_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid option: input must be yes/no (Error #100-10).
        /// </summary>
        internal static string Error_InvalidUseSsl_NotYesNo
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidUseSsl_NotYesNo", resourceCulture);
            }
        }
    }
}
