//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreySutton.Xrm.Utilities.Resources.ConsoleCrmCredentialManager
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreySutton.Xrm.Utilities.Resources.ConsoleCrmCredentialManager.Promp" +
                            "ts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Is Office365 [Yes/No]:.
        /// </summary>
        internal static string Prompt_IsOffice365
        {
            get
            {
                return ResourceManager.GetString("Prompt_IsOffice365", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Organization Name:.
        /// </summary>
        internal static string Prompt_OrganizationName
        {
            get
            {
                return ResourceManager.GetString("Prompt_OrganizationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Password:.
        /// </summary>
        internal static string Prompt_Password
        {
            get
            {
                return ResourceManager.GetString("Prompt_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Region [{0}-{1}]:.
        /// </summary>
        internal static string Prompt_Region
        {
            get
            {
                return ResourceManager.GetString("Prompt_Region", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Save Credentials (Encrypted) [Yes/No]:.
        /// </summary>
        internal static string Prompt_ShouldSaveCredentials
        {
            get
            {
                return ResourceManager.GetString("Prompt_ShouldSaveCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Unique Instance [Yes/No]:.
        /// </summary>
        internal static string Prompt_UniqueInstance
        {
            get
            {
                return ResourceManager.GetString("Prompt_UniqueInstance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Advanced Setup [Yes/No]:.
        /// </summary>
        internal static string Prompt_UseAdvancedSetup
        {
            get
            {
                return ResourceManager.GetString("Prompt_UseAdvancedSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Username:.
        /// </summary>
        internal static string Prompt_Username
        {
            get
            {
                return ResourceManager.GetString("Prompt_Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Use Saved Credentials [Yes/No]:.
        /// </summary>
        internal static string Prompt_UseSavedCredentials
        {
            get
            {
                return ResourceManager.GetString("Prompt_UseSavedCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Use SSL [Yes/No]:.
        /// </summary>
        internal static string Prompt_UseSsl
        {
            get
            {
                return ResourceManager.GetString("Prompt_UseSsl", resourceCulture);
            }
        }
    }
}
